agregar aplicaciones

diff --git a/.github/workflows/ci1.yml b/.github/workflows/ci1.yml
--- a/.github/workflows/ci1.yml
+++ b/.github/workflows/ci1.yml
@@ -244,14 +244,14 @@ jobs:
           done
 
           # Última verificación
-          docker-compose version || { echo "docker compose FAILED"; exit 1; }
+          sudo docker-compose version || { echo "docker compose FAILED"; exit 1; }
 
           # Exportar variables (poner aquí tus secrets)
           export WEATHER_API_KEY="${WEATHER_API_KEY}"
           export SECRET_KEY="${SECRET_KEY}"
 
-          docker-compose down
-          docker-compose up -d --build
+          sudo docker-compose down
+          sudo docker-compose up -d --build
           EOF
         env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
