Agrego puerto 5000

diff --git a/.github/workflows/ci1.yml b/.github/workflows/ci1.yml
--- a/.github/workflows/ci1.yml
+++ b/.github/workflows/ci1.yml
@@ -207,55 +207,55 @@ jobs:
 #            done
 #            echo "Docker did not become ready in time"
 #            exit 1
-      - name: Install Git on EC2
-        run: |
-          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ssh_key.pem
-          chmod 600 ssh_key.pem
+#      - name: Install Git on EC2
+#        run: |
+#          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ssh_key.pem
+#          chmod 600 ssh_key.pem
 
-          ssh -o StrictHostKeyChecking=no -i ssh_key.pem ubuntu@$EC2_IP << 'EOF'
-          sudo apt-get update -y
-          sudo apt-get install -y git
-          echo "Waiting for Docker inside EC2..."
-          for i in {1..15}; do
-           if command -v docker >/dev/null 2>&1; then
-             echo "Docker installed."
-             if sudo docker info >/dev/null 2>&1; then
-               echo "Docker daemon is ready!"
-               break
-             fi
-           fi
-           echo "Docker not ready yet... retrying"
-           sleep 15
-          done
-          # Clonar repositorio
-          if [ ! -d "proyecto" ]; then
-            git clone https://github.com/JimenaPereyra/mundoseproyecto1.git proyecto
-          fi
-          cd proyecto
+#          ssh -o StrictHostKeyChecking=no -i ssh_key.pem ubuntu@$EC2_IP << 'EOF'
+#          sudo apt-get update -y
+#          sudo apt-get install -y git
+#          echo "Waiting for Docker inside EC2..."
+#          for i in {1..15}; do
+#           if command -v docker >/dev/null 2>&1; then
+#             echo "Docker installed."
+#             if sudo docker info >/dev/null 2>&1; then
+#               echo "Docker daemon is ready!"
+#               break
+#             fi
+#           fi
+#           echo "Docker not ready yet... retrying"
+#           sleep 15
+#          done
+#          # Clonar repositorio
+#          if [ ! -d "proyecto" ]; then
+#            git clone https://github.com/JimenaPereyra/mundoseproyecto1.git proyecto
+#          fi
+#          cd proyecto
 
-          echo "Waiting for docker compose to be ready..."
-          for i in {1..15}; do
-            if docker compose version >/dev/null 2>&1; then
-              echo "docker compose is ready!"
-              break
-            fi
-            echo "docker compose not ready yet… retrying"
-            sleep 10
-          done
+#          echo "Waiting for docker compose to be ready..."
+#          for i in {1..15}; do
+#            if docker compose version >/dev/null 2>&1; then
+#              echo "docker compose is ready!"
+#              break
+#            fi
+#            echo "docker compose not ready yet… retrying"
+#            sleep 10
+#          done
 
-          # Última verificación
-          sudo docker-compose version || { echo "docker compose FAILED"; exit 1; }
+#          # Última verificación
+#          sudo docker-compose version || { echo "docker compose FAILED"; exit 1; }
 
-          # Exportar variables (poner aquí tus secrets)
-          export WEATHER_API_KEY="${WEATHER_API_KEY}"
-          export SECRET_KEY="${SECRET_KEY}"
+#          # Exportar variables (poner aquí tus secrets)
+#          export WEATHER_API_KEY="${WEATHER_API_KEY}"
+#          export SECRET_KEY="${SECRET_KEY}"
 
-          sudo docker-compose down
-          sudo docker-compose up -d --build
-          EOF
-        env:
-         WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
-         SECRET_KEY: ${{ secrets.SECRET_KEY }}
+#          sudo docker-compose down
+#          sudo docker-compose up -d --build
+#          EOF
+#        env:
+#         WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
+#         SECRET_KEY: ${{ secrets.SECRET_KEY }}
 #
 #      - name: Start Grafana on EC2
 #        uses: appleboy/ssh-action@v1.0.3
