agregar aplicaciones

diff --git a/.github/workflows/ci1.yml b/.github/workflows/ci1.yml
--- a/.github/workflows/ci1.yml
+++ b/.github/workflows/ci1.yml
@@ -232,6 +232,20 @@ jobs:
             git clone https://github.com/JimenaPereyra/mundoseproyecto1.git proyecto
           fi
           cd proyecto
+
+          echo "Waiting for docker compose to be ready..."
+          for i in {1..12}; do
+            if docker compose version >/dev/null 2>&1; then
+              echo "docker compose is ready!"
+              break
+            fi
+            echo "docker compose not ready yet… retrying"
+            sleep 5
+          done
+
+          # Última verificación
+          docker-compose version || { echo "docker compose FAILED"; exit 1; }
+
           # Exportar variables (poner aquí tus secrets)
           export WEATHER_API_KEY="${WEATHER_API_KEY}"
           export SECRET_KEY="${SECRET_KEY}"
